# Site settings
title: Partner Catalyst Team Case Studies
email: sarasp@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  testbed for case study publication
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://sarasp.github.io" # the base hostname & protocol for your site
twitter_username: saraspalding
github_username:  sarasp

# Build settings
markdown: redcarpet
# highlighter: pygments
extensions: [fenced_code_blocks]
